name: Docker build and push

on:
  push:
    branches:
      - '2-io'

env:
  USE_GHCR: '0'  # 设置 USE_GHCR 环境变量
  PLATFORMS: ${{ vars.PLATFORMS || 'linux/amd64' }}

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v2
        if: ${{ env.USE_GHCR != '1' }}
        with:
          username: ${{ secrets.DOCKERHUBACCOUNT }}
          password: ${{ secrets.DOCKERHUBPASS }}


      - name: Build and push
        uses: docker/build-push-action@v4
        if: ${{ env.USE_GHCR != '1' }}
        with:
          context: .
          platforms: ${{ vars.PLATFORMS }}
          push: true
          tags: ${{ github.actor }}/video2mp4
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Log into ghcr
        uses: docker/login-action@v2
        if: ${{ env.USE_GHCR == '1' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to ghcr
        uses: docker/build-push-action@v4
        if: ${{ env.USE_GHCR == '1' }}
        with:
          context: .
          platforms: ${{ vars.PLATFORMS }}
          push: true
          tags: ghcr.io/${{ github.actor }}/video2mp4
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
